apiVersion: v1
kind: Namespace
metadata:
  name: outer-worlds
---
apiVersion: v1
kind: Service
metadata:
  namespace: outer-worlds
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: out-wrd-dev-dev-rabbit-svc
  labels:
    app: out-wrd-dev
    tier: queue
    version: v1
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: out-wrd-dev
    tier: queue
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: outer-worlds
  name: out-wrd-dev-rabbit-dep
spec:
  selector:
    matchLabels:
      app: out-wrd-dev
      tier: queue
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: out-wrd-dev
        tier: queue
        version: v1
    spec:
      containers:
        - name: rabbitmq
          image: 'rabbitmq:3.7.17-alpine'
          resources:
            requests:
              cpu: 25m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 800Mi
          ports:
            - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  namespace: outer-worlds
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: out-wrd-dev-redis-svc
  labels:
    app: out-wrd-dev
    tier: persistence
    version: v1
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: out-wrd-dev
    tier: persistence
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: outer-worlds
  name: out-wrd-dev-redis-dep
spec:
  selector:
    matchLabels:
      app: out-wrd-dev
      tier: persistence
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: out-wrd-dev
        tier: persistence
        version: v1
    spec:
      containers:
        - name: redis
          image: 'redis:5.0.5-alpine3.10'
          resources:
            requests:
              cpu: 25m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 6379
---